增加12.1.0下载链接，添加天翼网盘下载说明
TieBaMma/InstallTutorial pull request #42
Opened 2020-05-24 03:39 UTC by ryaliu

## 摘要

- 增加12.1.0下载链接
- 添加天翼网盘下载说明
- 添加了官方淘宝店的购买导引
- 补全中文语言包全部下载站点

## 已知问题

- 由于 Wolfram 官方提供了 Linux 中文版，Mathematica 中文语言包不再更新，望知悉。

2020-05-24 05:34 UTC, merged

2020-05-24 05:34 UTC, Lemmingh requested changes

2020-05-24 05:34 UTC, Lemmingh commented on index.md
> +对于国内用户，可以在淘宝官方店铺 “Wolfram中国” 购买，该店铺提供含学生授权在内的多种许可证。
```suggestion
国内用户，可以在淘宝官方店铺 “[Wolfram中国](https://shop591547060.taobao.com/)” 购买，该店铺提供含学生授权在内的多种许可证。
```

添加链接。

另外，上下文语序是否也要调一下？

---

@TieBaMma
我记得中科院软件中心曾经来群里推销过，要不要也加上他们？<https://tieba.baidu.com/p/3815849376>

2020-05-24 05:34 UTC, Lemmingh commented on index.md
> +> * 标有 `API` 字样的 SharePoint / OneDrive 下载链接可以使用 Aria2 IDM 等第三方下载器下载。
```suggestion
> * 本文中标有 `API` 字样的 SharePoint / OneDrive 下载链接可以使用 Aria2、IDM 等第三方下载器下载。
```

2020-05-24 05:34 UTC, Lemmingh commented on index.md
> +> 天翼云盘也对单线程下载速度进行了限制，可以通过 Aria2 IDM 等软件进行多线程下载。
```suggestion
> 天翼云盘需要登陆才可以下载大于 300 MB 的文件，可以使用脚本 <https://greasyfork.org/scripts/397247-cloud-189-cn-download-without-login> 绕过登陆直接下载。
>
> 天翼云盘也会限制单线程下载速度，可以通过 Aria2、IDM 等软件进行多线程下载。
```

建议调整语序。
此外，最好把这个“注意”挪到列表上方，跟另外两个放在一起。

2020-05-24 05:34 UTC, Lemmingh commented
？？？

2020-05-24 05:44 UTC, TieBaMma commented on index.md
> +对于国内用户，可以在淘宝官方店铺 “Wolfram中国” 购买，该店铺提供含学生授权在内的多种许可证。
淘宝店应该就是他们开的@Lemmingh

2020-05-24 05:45 UTC, TieBaMma commented
居然出现了几乎同时在线的情况……

2020-05-24 07:11 UTC, ryaliu commented on index.md
> +对于国内用户，可以在淘宝官方店铺 “Wolfram中国” 购买，该店铺提供含学生授权在内的多种许可证。
看商家地址好像不是中科院软件中心？

我原本想加链接，结果手机淘宝复制出来是淘口令

2020-05-24 08:43 UTC, Lemmingh commented
如果我有 label 权限，也不至于出这乌龙。但是 GitHub 上权限切得不够细，没这种东西。😂

---

`revert-42-gh-pages` branch 如果没什么用，就删了吧。

2020-05-25 11:27 UTC, TieBaMma commented
@Lemmingh  我找不到`revert-42-gh-pages`在哪删……

2020-05-25 14:59 UTC, Lemmingh commented
<https://github.com/TieBaMma/InstallTutorial/branches>

你可能需要静下心来读一读 [Creating and deleting branches within your repository | GitHub Help](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-and-deleting-branches-within-your-repository)

2020-05-27 11:19 UTC, TieBaMma commented
> https://github.com/TieBaMma/InstallTutorial/branches
> 
> 你可能需要静下心来读一读 [Creating and deleting branches within your repository | GitHub Help](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-and-deleting-branches-within-your-repository)

搞定了……

2020-05-28 02:58 UTC, TieBaMma commented on index.md
> +对于国内用户，可以在淘宝官方店铺 “Wolfram中国” 购买，该店铺提供含学生授权在内的多种许可证。
@ryaliu 嗯？卖家地址是在哪看的？是要买了东西才能看的吗？
商家地址不是中科院软件中心并不奇怪吧，而且，如果 Wolfram中国 和 中科院软件中心 真是两个单位，那现在岂不是有两个Mathematica中文代理？（等下这好像也没什么奇怪的……？）

2020-05-28 04:15 UTC, Lemmingh commented on index.md
> +对于国内用户，可以在淘宝官方店铺 “Wolfram中国” 购买，该店铺提供含学生授权在内的多种许可证。
Wolfram 在中国的代理确实有一堆。

2020-05-28 04:25 UTC, ryaliu commented on index.md
> +对于国内用户，可以在淘宝官方店铺 “Wolfram中国” 购买，该店铺提供含学生授权在内的多种许可证。
![962BBEAE-2E0A-4A52-9205-472DC87D3139](https://user-images.githubusercontent.com/39220367/83098705-eba69180-a0dd-11ea-9cee-352f891b2340.jpeg)

上次应该是眼花了（我明明记得上次地址在华中哪个市的……）

Wolfram 在大陆的代理商一大堆，去锑度搜索 Mathematica ，推广区就能看到

2020-05-28 05:53 UTC, TieBaMma commented on index.md
> +对于国内用户，可以在淘宝官方店铺 “Wolfram中国” 购买，该店铺提供含学生授权在内的多种许可证。
WolframChina的微博主页给了个友链：https://mp.weixin.qq.com/s/taJHHebCQ5zDz8VtytIH2Q 列出的代理商没有中科院，感觉应该就是他们自己？话说新科学网（ http://www.newsciencecore.com/newscience/index.html ）已经404了……

2020-05-28 14:42 UTC, ryaliu commented on index.md
> +对于国内用户，可以在淘宝官方店铺 “Wolfram中国” 购买，该店铺提供含学生授权在内的多种许可证。
微信公众号（<https://mp.weixin.qq.com/s/taJHHebCQ5zDz8VtytIH2Q>）文章页面最下方给了这一淘宝店的链接，应该是WolframChina名下的。

另外，这里给出的部分代理商购买流程极其麻烦，有的代理商没给个人购买方式，只能批量购买；大部分代理商必须手动打电话发邮件，不能在线购买。

我建议把淘宝链接换成这篇文章的链接，附注一下淘宝店铺在页面最下方（是小字，容易看漏）。对普通人来说淘宝是最方便的购买途径。

（新科学网404是什么鬼……去年还好好的）

Wolfram 官网有个联系工单，可以试试问下中国区销售情况（有会中文的工作人员）。

2020-05-29 09:05 UTC, TieBaMma commented on index.md
> +对于国内用户，可以在淘宝官方店铺 “Wolfram中国” 购买，该店铺提供含学生授权在内的多种许可证。
思前想后还是把淘宝店的链接去掉了。不论是出于“道德”还是“安全”的考虑，这篇教程有必要保持“中立”。