更新 SharePoint-API 文件夹结构
TieBaMma/InstallTutorial pull request #59
Opened 2020-07-18 12:07 UTC by ryaliu

## 摘要

更新 SharePoint-API 文件夹结构，现在外层文件夹名尽量与官方仓库同步。
修订学生版授权：$80 是中国区特供价格。

2020-07-18 12:19 UTC, ryaliu commented
日常题外话：

1. 因为 OneManager-PHP 程序更新，`https://mmamirror.herokuapp.com/` 现已支持 JSON API，方法 Get，需要加 `?json` 参数。大概有人可以用来做个自动检测新版本？~~鸡肋功能+1~~

  > 示例： Get `https://mmamirror.herokuapp.com/share/Mathematica/?json`

2. 提供了 21Vianet （也就是世纪互联）的 SharePoint 下载源。因为我日常也得用 API 而且用量不小，而 API 调用次数是有限制的，这边调用多了我就没得用了，另外我也不希望这个世纪互联的 SharePoint 传太广，所以只是提供而不会放到项目主页等地宣传。有效期到明年七月。

> 用法：
> * 点一下 `21Vianet` 就切换到世纪互联的下载源了
![image](https://user-images.githubusercontent.com/39220367/87852354-c8f16600-c933-11ea-9dee-37189d48e51e.png)
> * 也可以把网址中的 `share` 换成 `vianet` ，不过两边的文件夹结构不太一样。

2020-07-18 13:59 UTC, Lemmingh commented
@ryaliu
⚠ **关掉**你那边的 GitHub Actions！

**Settings** > **Actions** > **Disable Actions for this repository**

否则，因为你现在正在 `gh-pages` 上工作，**明天早上**那个 workflow 一跑，你的东西就没了！

---

我过段时间会把它改成纯手动的。近期有点忙，没工夫处理。

2020-07-18 14:32 UTC, ryaliu commented
已关。~~还好顺手看了下邮箱~~

Repo Sync 还是先检查一下 commit 与原始仓库的情况吧……

我记得 `${{ secrets.GITHUB_TOKEN }}` 默认是不能用的，得用户自己去设置设一下叫这个名字的 Secret 变量？

2020-07-18 16:14 UTC, Lemmingh commented
> 先检查一下 commit 与原始仓库的情况

这……怎么实现？检查是否需要 *force push*，是否存在 PR 依赖？

那会很麻烦，不像是 checkout 几下，再 shell 跑几句的问题。恐怕需要自己写 action，而且很可能出现 GitHub API 调用。

我现在连模仿 [vscode-github-triage-actions](https://github.com/microsoft/vscode-github-triage-actions) 都做不到，如果真要动这种大工程，需要另请高明。

---

`GITHUB_TOKEN` 是系统自动生成的 PAT，对它自己**所处的 repo** 有 *write* 权限。

---

7 月 6 日刚放出一个新 feature：
[GitHub Actions: Manual triggers with `workflow_dispatch` | The GitHub Blog](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)

挺好使。

改代码容易，就 2 行：

```diff
-  schedule:
-    - cron: "0 0 * * 0"
+  workflow_dispatch:
```

但**写文档秃头**。很抱歉，我近期没精力遣词造句。

2020-07-18 17:12 UTC, Lemmingh requested changes

2020-07-18 17:12 UTC, Lemmingh commented on index.md
> +如果不想付钱也想用学生版而学校也没买，可以考虑参加 [wolfram 的学生大使计划](https://www.wolfram.com/company/careers/ambassador/index.html.zh?footer=lang)。
```suggestion
如果想用学生版，但是学校没买又不想自己付钱，可以考虑参加 [Wolfram 学生大使计划](https://www.wolfram.com/company/careers/ambassador/)。
```

<https://www.wolfram.com/resources/>
<https://www.wolfram.com/company/careers/ambassador/>
这两个页面上显示的名称不一样，出现这种分歧，确实挺离谱。

而且 Wolfram 的页面没有设置 canonical link，只能靠 300 推测。🤦

2020-07-19 02:48 UTC, ryaliu commented on index.md
> +如果不想付钱也想用学生版而学校也没买，可以考虑参加 [wolfram 的学生大使计划](https://www.wolfram.com/company/careers/ambassador/index.html.zh?footer=lang)。
Wolfram 的员工称之为“学生大使计划”，而且官方大部分宣传写的也是“计划”

2020-07-19 02:50 UTC, ryaliu commented on index.md
> +如果不想付钱也想用学生版而学校也没买，可以考虑参加 [wolfram 的学生大使计划](https://www.wolfram.com/company/careers/ambassador/index.html.zh?footer=lang)。
另外 `index.html.zh` 可以强行指定使用中文，Wolfram 的网站部分浏览器做不到按语言跳转。

2020-07-19 03:16 UTC, Lemmingh commented on index.md
> +如果不想付钱也想用学生版而学校也没买，可以考虑参加 [wolfram 的学生大使计划](https://www.wolfram.com/company/careers/ambassador/index.html.zh?footer=lang)。
好的，你看现在这样如何？

2020-07-19 03:47 UTC, Lemmingh commented on index.md
> +如果不想付钱也想用学生版而学校也没买，可以考虑参加 [wolfram 的学生大使计划](https://www.wolfram.com/company/careers/ambassador/index.html.zh?footer=lang)。
语言问题跟 `Accept-Language` 有关。响应的 `Content-Language` 和 `Content-Location` 随请求的 `Accept-Language` 改变。

目前试出来：`zh` 的权重较高时，返回中文。

而且 Wolfram 能识别的语言代码似乎很少。如果我写 `zh-Hans` `zh-CN`，它就不认识了，会返回英文。😨

2020-07-19 05:18 UTC, Lemmingh commented
**Request**

```http
GET https://mmamirror.herokuapp.com/share/Mathematica/?json HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
```

**Response**

```http
HTTP/1.1 200 OK
Date: Sun, 19 Jul 2020 04:01:42 GMT
Server: Apache
Transfer-Encoding: chunked
Content-Type: text/html;charset=UTF-8
Via: 1.1 vegur

{"list":[{"type":1,"id":"01TANQYNZ66CV3NGW5ABCLOMPZBM4INCM3","name":"12.1.0.0","time":"2020-07-18T11:53:07Z","size":15837550151,"mime":null},{"type":1,"id":"01TANQYN3M6DN6WHCEVFGLGY3CTIGH6OKQ","name":"12.1.1.0","time":"2020-07-18T11:53:13Z","size":14337147748,"mime":null}]}
```

```json
{
  "list": [
    {
      "type": 1,
      "id": "01TANQYNZ66CV3NGW5ABCLOMPZBM4INCM3",
      "name": "12.1.0.0",
      "time": "2020-07-18T11:53:07Z",
      "size": 15837550151,
      "mime": null
    },
    {
      "type": 1,
      "id": "01TANQYN3M6DN6WHCEVFGLGY3CTIGH6OKQ",
      "name": "12.1.1.0",
      "time": "2020-07-18T11:53:13Z",
      "size": 14337147748,
      "mime": null
    }
  ]
}
```

* 没想到怎么用……
* 响应头如果设置 `Content-Type: application/json`，可能会友善一些。

2020-07-19 07:49 UTC, ryaliu commented on index.md
> +如果不想付钱也想用学生版而学校也没买，可以考虑参加 [wolfram 的学生大使计划](https://www.wolfram.com/company/careers/ambassador/index.html.zh?footer=lang)。
Safari 简体中文相关的 `Accept-Language` 头只有 `zh-Hans-**`（`**` 是设置的地区），所以一直是英文。新版好像加了`zh`，但我一直没更新系统。

2020-07-19 07:57 UTC, ryaliu commented
> 没想到怎么用……
>
> 响应头如果设置 `Content-Type: application/json`，可能会友善一些。

https://github.com/qkqpttgf/OneManager-php 最近更新才提供的功能，或许可以去他的 issue 区提交一下？

我也不知道能拿来干啥，这东西还特别耗微软 API 用量……

2020-07-19 18:00 UTC, Lemmingh commented on index.md
> +如果不想付钱也想用学生版而学校也没买，可以考虑参加 [wolfram 的学生大使计划](https://www.wolfram.com/company/careers/ambassador/index.html.zh?footer=lang)。
[Firefox](https://support.mozilla.org/en-US/kb/choose-display-languages-multilingual-web-pages)，以及 [Windows 和 Chromebook 上的 Chrome](https://support.google.com/chrome/answer/173424) 可以随意调 `Accept-Language`。

Safari 似乎不能。但它竟然有 [**Disable Cross-Origin Restrictions**](https://support.apple.com/zh-cn/guide/safari-developer/dev39df999c1/mac) 这种骚操作。😂

**参看**

* [How to Change Language in Google Chrome | Beebom](https://beebom.com/change-language-google-chrome/)
* [Setting language preferences in a browser | W3C ](https://www.w3.org/International/questions/qa-lang-priorities.en)

2020-07-20 01:58 UTC, ryaliu commented on index.md
> +如果不想付钱也想用学生版而学校也没买，可以考虑参加 [wolfram 的学生大使计划](https://www.wolfram.com/company/careers/ambassador/index.html.zh?footer=lang)。
我比较暴力，直接拿 Header Editor 改请求头（

2020-07-22 14:49 UTC, Lemmingh commented
头的问题已报告在 qkqpttgf/OneManager-php#95

---

消耗大应该是因为 SharePoint API 不能直接返回文件夹的大小，需要列出整个目录树，求和。

2020-07-23 04:00 UTC, TieBaMma commented
……这个是多长时间自动 merge 一次？还是需要我点什么？

2020-07-23 04:51 UTC, Lemmingh commented
@TieBaMma
**Files changed** > **Review changes** > **Approve** > **Submit review**

目前，你是唯一拥有 *write* access 的人，所以，只有你有权执行这项操作。

Mergify 会在 **Checks** 中汇报它的运行状况。

<https://docs.github.com/en/articles/approving-a-pull-request-with-required-reviews>
<https://doc.mergify.io/conditions.html#attributes>

（`CONTRIBUTING.md` 里有介绍）

2020-07-23 05:41 UTC, TieBaMma approved these changes

2020-07-23 05:43 UTC, merged