wolfram engine 12.1.0 win 直链
TieBaMma/InstallTutorial pull request #66
Opened 2020-08-06 16:45 UTC by wz1765

客服直链

2020-08-07 10:06 UTC, Lemmingh requested changes

2020-08-07 10:06 UTC, Lemmingh commented on index.md
> +
```suggestion

* (12.1.0) Windows
  * [Wolfram 客服直链](https://amoeba.wolfram.com/index.php/s/tpJSq7FJsn99XXR)
```

排版

2020-08-07 12:08 UTC, TieBaMma approved these changes

2020-08-07 12:11 UTC, merged

2020-08-10 02:33 UTC, Lemmingh commented
@wz1765

> [@ryaliu](https://github.com/TieBaMma/InstallTutorial/commit/64560b0a4b6a65dd106fa54c6e8b63218a4fd387#commitcomment-41318796)
>
> 贴客服直链有征得官方同意吗？

Ref:

> 按照每个用户占用 1hr 机时、25% 用户是正版用户，每个用户平均下载 4GiB 文件计算，非正版用户会给 Wolfram 公司产生 638 元人民币左右的额外成本。实际值只会更高不会更低。

---

感谢 @ryaliu 的提醒。

2020-08-10 03:15 UTC, TieBaMma commented
嗯……可是 Wolfram Engine 本来就是个免费产品啊。

2020-08-10 03:39 UTC, Lemmingh commented
问题变得复杂起来。可能我不该引述另外一段。😅

这里的核心问题是：

**是否可以公开 Wolfram 的直链。**

这是一个有关**授权**的问题。

进而引申：

* 如果为我们认为，所有直链都是 Wolfram 私有的财产。那么**自行公开**直链是合适的吗？
* 如果为我们认为，Wolfram **默许**公开免费产品的直链。那就没什么需要讨论的了。

2020-08-10 03:49 UTC, ryaliu commented
amoeba.wolfram.com 是 WRL 的私有云，不是公开储存

2020-08-10 11:51 UTC, TieBaMma commented
行吧，那暂且先撤下。